[tool.poetry]
name = "snaky_bucket"
version = "0.1.0"
description = ""
authors = ["vutr <me@vutr.io>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
autopep8 = "^1.4"
flake8 = "^3.7"
pylint = "^2.4"
logzero = "^1.5"
pytest-cov = "^2.8"

[tool.poetry.scripts]
test = 'scripts:test'
lint = 'scripts:lint'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"